using System.Windows.Forms;//using windows forms

namespace Project //define the namespace for the Windows Forms application
{
    partial class Form_display  //partial class initialization
    {
        private System.ComponentModel.IContainer components = null;// This variable holds the container for components used in the Windows Form.

        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)//overide to dispose 
        {
            // Check if disposing is true, meaning managed resources should be disposed.
            if (disposing && (components != null))
            {
                // Dispose of the components if they exist.
                components.Dispose();
            }
            // Call the base class Dispose method to clean up.
            base.Dispose(disposing);
        }

        //region generated by designer
        #region Windows Form Designer generated code// This region contains code generated by the Windows Form Designer. 

        private void InitializeComponent()  //initialize components constructor
        {
            this.components = new System.ComponentModel.Container();    // Initialize the components container
            
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea11 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();// Create instances of chart area 11 for the candlestick chart
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea12 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();// Create instances of chart area 12 for the candlestick chart
            System.Windows.Forms.DataVisualization.Charting.Legend legend = new System.Windows.Forms.DataVisualization.Charting.Legend();// Create a legend for the chart
            System.Windows.Forms.DataVisualization.Charting.Series series11 = new System.Windows.Forms.DataVisualization.Charting.Series(); // Create series 11 for the chart data
            System.Windows.Forms.DataVisualization.Charting.Series series12 = new System.Windows.Forms.DataVisualization.Charting.Series(); // Create series 12 for the chart data
            this.chart_candlesticks = new System.Windows.Forms.DataVisualization.Charting.Chart();  // Initialize the candlestick chart
            this.dateTimePicker_endDate = new System.Windows.Forms.DateTimePicker();    // Initialize end date time picker for start and end dates
            this.label_endDate = new System.Windows.Forms.Label();  // Initialize end date 
            this.dateTimePicker_startDate = new System.Windows.Forms.DateTimePicker();  // Initialize start date time picker
            this.label_startDate = new System.Windows.Forms.Label();    // Initialize start date
            this.button_update = new System.Windows.Forms.Button(); // Initialize update buttons for updating and showing peaks/valleys
            this.aCandlestickBindingSource = new System.Windows.Forms.BindingSource(this.components);   //binding candlesticks
            this.directorySearcher1 = new System.DirectoryServices.DirectorySearcher(); //use directory searcher for candlestick binding
            this.openFileDialog_load = new System.Windows.Forms.OpenFileDialog();   //load open file dialog
            this.button2 = new System.Windows.Forms.Button();   //initialize button 2 
            this.button_showPeaks = new System.Windows.Forms.Button();  //initialize button to show peaks
            this.button_showValleys = new System.Windows.Forms.Button();    //initialize button to show valleys
            ((System.ComponentModel.ISupportInitialize)(this.chart_candlesticks)).BeginInit();  // Begin initialization for the candlestick chart 
            ((System.ComponentModel.ISupportInitialize)(this.aCandlestickBindingSource)).BeginInit();   // Begin initialization for data binding source
            this.SuspendLayout();   // Set up the form layout and properties (not shown in the snippet)
            // Additional configuration for components would go here (not shown in the snippet)
        
            // chart_candlesticks
            // Align the first chart area with the volume chart area and name it
            chartArea11.AlignWithChartArea = "ChartArea_Volume"; // Set alignment with volume chart area
            chartArea11.Name = "ChartArea_OHLC"; // Name the chart area for Open-High-Low-Close (OHLC) data

            // Align the second chart area with the OHLC chart area and name it
            chartArea12.AlignWithChartArea = "ChartArea_OHLC"; // Set alignment with OHLC chart area
            chartArea12.Name = "ChartArea_Volume"; // Name the chart area for volume data

            this.chart_candlesticks.ChartAreas.Add(chartArea11);// Add the chart area 11 to the candlestick chart
            this.chart_candlesticks.ChartAreas.Add(chartArea12);// Add the chart areas 12 to the candlestick chart

            // Set the docking style of the chart to the top of the container
            this.chart_candlesticks.Dock = System.Windows.Forms.DockStyle.Top;

            // Configure the legend; disable it and set its name
            legend.Enabled = false; // Disable the legend
            legend.Name = "Legend1"; // Name the legend

            // Add the legend to the candlestick chart
            this.chart_candlesticks.Legends.Add(legend);

            // Set the location and name of the candlestick chart
            this.chart_candlesticks.Location = new System.Drawing.Point(0, 0); // Set the position of the chart
            this.chart_candlesticks.Name = "chart_candlesticks"; // Name the chart

            // Configure the first series for OHLC data
            series11.ChartArea = "ChartArea_OHLC"; // Specify the chart area for this series
            series11.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Candlestick; // Set the series type to Candlestick
            series11.CustomProperties = "PriceDownColor=Red, PriceUpColor=Green"; // Set custom properties for price colors
            series11.IsXValueIndexed = true; // Enable indexing for X values
            series11.Legend = "Legend1"; // Associate the series with the legend
            series11.Name = "Series_OHLC"; // Name the series for OHLC data
            series11.XValueMember = "Date"; // Set the member for X values
            series11.XValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.DateTime; // Define the type for X values as DateTime
            series11.YValueMembers = "High,Low,Open,Close"; // Set the Y value members for the series
            series11.YValuesPerPoint = 6; // Specify the number of Y values per point

            // Configure the second series for volume data
            series12.ChartArea = "ChartArea_Volume"; // Specify the chart area for this series
            series12.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.StackedColumn; // Set the series type to StackedColumn
            series12.IsXValueIndexed = true; // Enable indexing for X values
            series12.Legend = "Legend1"; // Associate the series with the legend
            series12.Name = "Series_Volume"; // Name the series for volume data
            series12.XValueMember = "Date"; // Set the member for X values
            series12.XValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.DateTime; // Define the type for X values as DateTime
            series12.YValueMembers = "Volume"; // Set the Y value member for the series
            series12.YValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.UInt64; // Define the type for Y values as unsigned 64-bit integer
            this.chart_candlesticks.Series.Add(series11);   //chart for series 11
            this.chart_candlesticks.Series.Add(series12);   //chart for series 12

            // Set the size of the candlestick chart
            this.chart_candlesticks.Size = new System.Drawing.Size(1453, 693); // Specify the dimensions of the chart

            // Set the tab index for the chart
            this.chart_candlesticks.TabIndex = 3; // Set the tab index for navigation

            // Set the text for the chart
            this.chart_candlesticks.Text = "Candlesticks Chart"; // Assign a title to the chart

            // Attach an event handler for the chart click event
            this.chart_candlesticks.Click += new System.EventHandler(this.chart1_Click); // Define the event for clicks on the chart

            // dateTimePicker_endDate
            // Set the location of the end date DateTimePicker control on the form
            this.dateTimePicker_endDate.Location = new System.Drawing.Point(684, 702); // Specify the (x, y) coordinates for the DateTimePicker position

            // Set the maximum date that can be selected in the DateTimePicker
            this.dateTimePicker_endDate.MaxDate = new System.DateTime(2100, 10, 29, 0, 0, 0, 0); // Limit selection to dates up to October 29, 2100

            // Set the name of the DateTimePicker control for identification
            this.dateTimePicker_endDate.Name = "dateTimePicker_endDate"; // Assign a name for the control

            // Set the size of the DateTimePicker control
            this.dateTimePicker_endDate.Size = new System.Drawing.Size(270, 22); // Specify the width and height of the control

            // Set the tab index for the DateTimePicker for navigation purposes
            this.dateTimePicker_endDate.TabIndex = 5; // Specify the order of focus when navigating through controls

            // Set the default value of the DateTimePicker to October 29, 2024
            this.dateTimePicker_endDate.Value = new System.DateTime(2024, 10, 29, 0, 0, 0, 0); // Assign the default selected date and time

            // label_endDate
            // Set the AutoSize property to true, allowing the label to resize based on its content
            this.label_endDate.AutoSize = true; // Automatically adjusts the label size to fit the text

            // Set the location of the label on the form
            this.label_endDate.Location = new System.Drawing.Point(768, 727); // Specify the (x, y) coordinates for the label position

            // Set the name of the label for identification
            this.label_endDate.Name = "label_endDate"; // Assign a name to the label

            // Set the size of the label control
            this.label_endDate.Size = new System.Drawing.Size(81, 16); // Specify the width and height of the label

            // Set the tab index for the label for navigation purposes
            this.label_endDate.TabIndex = 9; // Specify the order of focus when navigating through controls

            // Set the text displayed on the label
            this.label_endDate.Text = "Ending Date"; // Assign the text that will be shown on the label

            // Attach an event handler for the label click event
            this.label_endDate.Click += new System.EventHandler(this.label2_Click); // Define the event for clicks on the label

            // dateTimePicker_startDate
            // Set the accessible name for the DateTimePicker, used for accessibility purposes
            this.dateTimePicker_startDate.AccessibleName = ""; // Leave empty, can be set for screen readers

            // Set the location of the start date DateTimePicker control on the form
            this.dateTimePicker_startDate.Location = new System.Drawing.Point(78, 702); // Specify the (x, y) coordinates for the DateTimePicker position

            // Set the name of the DateTimePicker control for identification
            this.dateTimePicker_startDate.Name = "dateTimePicker_startDate"; // Assign a name for the control

            // Set the size of the DateTimePicker control
            this.dateTimePicker_startDate.Size = new System.Drawing.Size(242, 22); // Specify the width and height of the control

            // Set the tab index for the DateTimePicker for navigation purposes
            this.dateTimePicker_startDate.TabIndex = 4; // Specify the order of focus when navigating through controls

            // Set the default value of the DateTimePicker to January 1, 2024, at 15:35
            this.dateTimePicker_startDate.Value = new System.DateTime(2024, 1, 1, 15, 35, 0, 0); // Assign the default selected date and time

            // Attach an event handler for the value change event of the DateTimePicker
            this.dateTimePicker_startDate.ValueChanged += new System.EventHandler(this.dateTimePicker_startDate_ValueChanged); // Define the event for changes in the selected date

            // label_startDate
            // Set the AutoSize property to true, allowing the label to resize based on its content
            this.label_startDate.AutoSize = true; // Automatically adjusts the label size to fit the text

            // Set the location of the label on the form
            this.label_startDate.Location = new System.Drawing.Point(131, 727); // Specify the (x, y) coordinates for the label position

            // Set the name of the label for identification
            this.label_startDate.Name = "label_startDate"; // Assign a name to the label

            // Set the size of the label control
            this.label_startDate.Size = new System.Drawing.Size(84, 16); // Specify the width and height of the label

            // Set the tab index for the label for navigation purposes
            this.label_startDate.TabIndex = 8; // Specify the order of focus when navigating through controls

            // Set the text displayed on the label
            this.label_startDate.Text = "Starting Date"; // Assign the text that will be shown on the label

            // Attach an event handler for the label click event
            this.label_startDate.Click += new System.EventHandler(this.label1_Click); // Define the event for clicks on the label

            // button_update
            // Set the location of the update button on the form
            this.button_update.Location = new System.Drawing.Point(517, 702); // Specify the (x, y) coordinates for the button position

            // Set the name of the button for identification
            this.button_update.Name = "button_update"; // Assign a name to the button

            // Set the size of the button control
            this.button_update.Size = new System.Drawing.Size(139, 39); // Specify the width and height of the button

            // Set the tab index for the button for navigation purposes
            this.button_update.TabIndex = 6; // Specify the order of focus when navigating through controls

            // Set the text displayed on the button
            this.button_update.Text = "Refresh"; // Assign the text that will be shown on the button

            // Set the button to use the visual style of the application
            this.button_update.UseVisualStyleBackColor = true; // Enable the use of visual styles for the button

            // Attach an event handler for the button click event
            this.button_update.Click += new System.EventHandler(this.button_update_Click); // Define the event for clicks on the button

            // directorySearcher1
            // Set the client timeout for the directory search operation
            this.directorySearcher1.ClientTimeout = System.TimeSpan.Parse("-00:00:01"); // Set a timeout of 1 second for client operations

            // Set the server page time limit for the directory search operation
            this.directorySearcher1.ServerPageTimeLimit = System.TimeSpan.Parse("-00:00:01"); // Set a timeout of 1 second for server page responses

            // Set the server time limit for the directory search operation
            this.directorySearcher1.ServerTimeLimit = System.TimeSpan.Parse("-00:00:01"); // Set a timeout of 1 second for server operations

            // openFileDialog_load
            // Set the default file name for the open file dialog
            this.openFileDialog_load.FileName = "IBM-Month.csv"; // Specify the default file name to be loaded

            // Set the filter for the file types in the open file dialog
            this.openFileDialog_load.Filter = "All Files|*.csv|Monthly|-Month.csv"; // Define the filter options for file selection

            // Allow multiple file selection in the open file dialog
            this.openFileDialog_load.Multiselect = true; // Enable the selection of multiple files

            // Attach an event handler for the file dialog's FileOk event
            this.openFileDialog_load.FileOk += new System.ComponentModel.CancelEventHandler(this.openFileDialog_load_FileOk); // Define the event for when a file is selected

            // button2
            // Set the location of button2 control on the form
            this.button2.Location = new System.Drawing.Point(351, 702); // Specify the (x, y) coordinates for the button position

            // Set the name of button2 for identification
            this.button2.Name = "button2"; // Assign a name to the button

            // Set the size of button2 control
            this.button2.Size = new System.Drawing.Size(139, 39); // Specify the width and height of the button

            // Set the tab index for button2 for navigation purposes
            this.button2.TabIndex = 12; // Specify the order of focus when navigating through controls

            // Set the text displayed on button2
            this.button2.Text = "Load Stock"; // Assign the text that will be shown on the button

            // Set the button to use the visual style of the application
            this.button2.UseVisualStyleBackColor = true; // Enable the use of visual styles for the button

            // Attach an event handler for the button click event
            this.button2.Click += new System.EventHandler(this.button_load_Click); // Define the event for clicks on button2

            // button_showPeaks
            // Set the location of the button_showPeaks control on the form
            this.button_showPeaks.Location = new System.Drawing.Point(1006, 699); // Specify the (x, y) coordinates for the button position

            // Set the name of button_showPeaks for identification
            this.button_showPeaks.Name = "button_showPeaks"; // Assign a name to the button

            // Set the size of button_showPeaks control
            this.button_showPeaks.Size = new System.Drawing.Size(139, 39); // Specify the width and height of the button

            // Set the tab index for button_showPeaks for navigation purposes
            this.button_showPeaks.TabIndex = 13; // Specify the order of focus when navigating through controls

            // Set the text displayed on button_showPeaks
            this.button_showPeaks.Text = "Show Peaks"; // Assign the text that will be shown on the button

            // Set the button to use the visual style of the application
            this.button_showPeaks.UseVisualStyleBackColor = true; // Enable the use of visual styles for the button

            // Attach an event handler for the button_showPeaks click event
            this.button_showPeaks.Click += new System.EventHandler(this.button_showPeaks_Click); // Define the event for clicks on button_showPeaks
 
            // button_showValleys
            // Set the location of the button_showValleys control on the form
            this.button_showValleys.Location = new System.Drawing.Point(1202, 699); // Specify the (x, y) coordinates for the button position

            // Set the name of button_showValleys for identification
            this.button_showValleys.Name = "button_showValleys"; // Assign a name to the button

            // Set the size of button_showValleys control
            this.button_showValleys.Size = new System.Drawing.Size(139, 39); // Specify the width and height of the button

            // Set the tab index for button_showValleys for navigation purposes
            this.button_showValleys.TabIndex = 14; // Specify the order of focus when navigating through controls

            // Set the text displayed on button_showValleys
            this.button_showValleys.Text = "Show Valleys"; // Assign the text that will be shown on the button

            // Set the button to use the visual style of the application
            this.button_showValleys.UseVisualStyleBackColor = true; // Enable the use of visual styles for the button

            // Attach an event handler for the button_showValleys click event
            this.button_showValleys.Click += new System.EventHandler(this.button_showValleys_Click); // Define the event for clicks on button_showValleys

            // Form Display Configuration 
            // Set the scaling dimensions for the form, defining the size of the text and controls
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F); // Set the scaling factor for the form

            // Set the scaling mode to font-based scaling
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font; // Enable automatic scaling based on the font size

            // Set the client area size of the form
            this.ClientSize = new System.Drawing.Size(1453, 756); // Specify the width and height of the form

            // Add controls to the form
            this.Controls.Add(this.button_showValleys); // Add the button for showing valleys
            this.Controls.Add(this.button_showPeaks); // Add the button for showing peaks
            this.Controls.Add(this.button2); // Add the button for loading stock
            this.Controls.Add(this.label_endDate); // Add the label for the end date
            this.Controls.Add(this.label_startDate); // Add the label for the start date
            this.Controls.Add(this.button_update); // Add the button for refreshing data
            this.Controls.Add(this.dateTimePicker_endDate); // Add the DateTimePicker for selecting the end date
            this.Controls.Add(this.dateTimePicker_startDate); // Add the DateTimePicker for selecting the start date
            this.Controls.Add(this.chart_candlesticks); // Add the candlestick chart

            // Set the name of the form for identification
            this.Name = "Form_display"; //name to the form

            // Set the title text displayed on the form
            this.Text = "Form_display"; //title for the form window

            // Attach an event handler for the form's Load event
            this.Load += new System.EventHandler(this.Form_display_Load); //event for when the form is loaded

            // End the initialization of the chart and data binding source
            ((System.ComponentModel.ISupportInitialize)(this.chart_candlesticks)).EndInit(); // End initialization for the chart
            ((System.ComponentModel.ISupportInitialize)(this.aCandlestickBindingSource)).EndInit(); // End initialization for the binding source

            // Initialize timer for simulation, set interval to 100ms and attach event handler for tick event
            this.timer_simulation = new System.Windows.Forms.Timer(this.components);
            this.timer_simulation.Interval = 100;
            this.timer_simulation.Tick += new System.EventHandler(this.timer_simulation_Tick);

            // Initialize Start/Stop button, set its location, size, text, and attach click event handler
            this.button_startStop = new System.Windows.Forms.Button();
            this.button_startStop.Location = new System.Drawing.Point(1000, 750);
            this.button_startStop.Name = "button_startStop";
            this.button_startStop.Size = new System.Drawing.Size(139, 39);
            this.button_startStop.TabIndex = 15;
            this.button_startStop.Text = "Start";
            this.button_startStop.UseVisualStyleBackColor = true;
            this.button_startStop.Click += new System.EventHandler(this.button_startStop_Click);

            // Initialize Increase button, set its location, size, text, and attach click event handler
            this.button_increase = new System.Windows.Forms.Button();
            this.button_increase.Location = new System.Drawing.Point(1150, 750);
            this.button_increase.Name = "button_increase";
            this.button_increase.Size = new System.Drawing.Size(50, 39);
            this.button_increase.TabIndex = 16;
            this.button_increase.Text = "+";
            this.button_increase.UseVisualStyleBackColor = true;
            this.button_increase.Click += new System.EventHandler(this.button_increase_Click);

            // Initialize Decrease button, set its location, size, text, and attach click event handler
            this.button_decrease = new System.Windows.Forms.Button();
            this.button_decrease.Location = new System.Drawing.Point(1210, 750);
            this.button_decrease.Name = "button_decrease";
            this.button_decrease.Size = new System.Drawing.Size(50, 39);
            this.button_decrease.TabIndex = 17;
            this.button_decrease.Text = "-";
            this.button_decrease.UseVisualStyleBackColor = true;
            this.button_decrease.Click += new System.EventHandler(this.button_decrease_Click);

            // Initialize Min Price label, set its location and text
            this.label_minPrice = new System.Windows.Forms.Label();
            this.label_minPrice.AutoSize = true;
            this.label_minPrice.Location = new System.Drawing.Point(78, 760);
            this.label_minPrice.Name = "label_minPrice";
            this.label_minPrice.Size = new System.Drawing.Size(120, 16);
            this.label_minPrice.Text = "Min Price (%)";

            // Initialize Min Price textbox, set its location, size, and default text
            this.textBox_minPricePercent = new System.Windows.Forms.TextBox();
            this.textBox_minPricePercent.Location = new System.Drawing.Point(210, 760);
            this.textBox_minPricePercent.Name = "textBox_minPricePercent";
            this.textBox_minPricePercent.Size = new System.Drawing.Size(70, 22);
            this.textBox_minPricePercent.TabIndex = 18;
            this.textBox_minPricePercent.Text = "0";

            // Initialize Max Price label, set its location and text
            this.label_maxPrice = new System.Windows.Forms.Label();
            this.label_maxPrice.AutoSize = true;
            this.label_maxPrice.Location = new System.Drawing.Point(300, 760);
            this.label_maxPrice.Name = "label_maxPrice";
            this.label_maxPrice.Size = new System.Drawing.Size(120, 16);
            this.label_maxPrice.Text = "Max Price (%)";

            // Initialize Max Price textbox, set its location, size, and default text
            this.textBox_maxPricePercent = new System.Windows.Forms.TextBox();
            this.textBox_maxPricePercent.Location = new System.Drawing.Point(430, 760);
            this.textBox_maxPricePercent.Name = "textBox_maxPricePercent";
            this.textBox_maxPricePercent.Size = new System.Drawing.Size(70, 22);
            this.textBox_maxPricePercent.TabIndex = 19;
            this.textBox_maxPricePercent.Text = "100";

            // Initialize Step Size label, set its location and text
            this.label_stepSize = new System.Windows.Forms.Label();
            this.label_stepSize.AutoSize = true;
            this.label_stepSize.Location = new System.Drawing.Point(520, 760);
            this.label_stepSize.Name = "label_stepSize";
            this.label_stepSize.Size = new System.Drawing.Size(90, 16);
            this.label_stepSize.Text = "Step Size (%)";

            // Initialize Step Size textbox, set its location, size, and default text
            this.textBox_stepSize = new System.Windows.Forms.TextBox();
            this.textBox_stepSize.Location = new System.Drawing.Point(620, 760);
            this.textBox_stepSize.Name = "textBox_stepSize";
            this.textBox_stepSize.Size = new System.Drawing.Size(70, 22);
            this.textBox_stepSize.TabIndex = 20;
            this.textBox_stepSize.Text = "5";

            // Initialize Waves ComboBox, set its location, size, and default text, and attach event handler
            this.comboBox_waves = new System.Windows.Forms.ComboBox();
            this.comboBox_waves.Location = new System.Drawing.Point(700, 760);
            this.comboBox_waves.Name = "comboBox_waves";
            this.comboBox_waves.Size = new System.Drawing.Size(280, 24);
            this.comboBox_waves.TabIndex = 21;
            this.comboBox_waves.Text = "Select a Wave";
            this.comboBox_waves.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox_waves.SelectedIndexChanged += new System.EventHandler(this.comboBox_waves_SelectedIndexChanged);

            // Add all controls to the form's Controls collection
            this.Controls.Add(this.button_startStop);
            this.Controls.Add(this.button_increase);
            this.Controls.Add(this.button_decrease);
            this.Controls.Add(this.textBox_minPricePercent);
            this.Controls.Add(this.textBox_maxPricePercent);
            this.Controls.Add(this.textBox_stepSize);
            this.Controls.Add(this.label_minPrice);
            this.Controls.Add(this.label_maxPrice);
            this.Controls.Add(this.label_stepSize);
            this.Controls.Add(this.comboBox_waves);


            // Resume the layout logic for the form
            this.ResumeLayout(false); // Resume layout logic for controls on the form
            this.PerformLayout(); // Perform layout logic for controls, ensuring they are correctly arranged
        }

            #endregion
            // Control Declarations
            // Declare a binding source for the candlestick data
            private System.Windows.Forms.BindingSource aCandlestickBindingSource; 

            // Declare the candlestick chart
            private System.Windows.Forms.DataVisualization.Charting.Chart chart_candlesticks; 

            // Declare the DateTimePicker for the end date
            private DateTimePicker dateTimePicker_endDate; 

            // Declare the label for the end date
            private Label label_endDate; 

            // Declare the DateTimePicker for the start date
            private DateTimePicker dateTimePicker_startDate; 

            // Declare the label for the start date
            private Label label_startDate; 

            // Declare the button for updating/refreshing data
            private Button button_update; 

            // Declare the directory searcher for querying directory services
            private System.DirectoryServices.DirectorySearcher directorySearcher1; 

            // Declare the open file dialog for loading files
            private OpenFileDialog openFileDialog_load; 

            // Declare button2 for loading stock data
            private Button button2; 

            // Declare the button for showing peaks
            private Button button_showPeaks; 

            // Declare the button for showing valleys
            private Button button_showValleys; 

            // Add these control declarations with the other controls
            private Button button_startStop;
            private Button button_increase;
            private Button button_decrease;
            private System.Windows.Forms.Timer timer_simulation;
            private TextBox textBox_minPricePercent;
            private TextBox textBox_maxPricePercent;
            private TextBox textBox_stepSize;
            private Label label_minPrice;
            private Label label_maxPrice;
            private Label label_stepSize;
            private ComboBox comboBox_waves;
    }
}